# Generated by Django 6.0.6 on 2026-06-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(choices=[('user', 'User (The human)'), ('ai', 'AI (The robot)')], max_length=10),
        ),
    ]
